{{- if .Values.webapp.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "s3www.fullname" . }}-webapp-ingress
  {{- if .Values.webapp.namespace }}
  namespace: {{ .Values.webapp.namespace }}
  {{- end }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  {{- with .Values.webapp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.webapp.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.webapp.ingress.tls }}
  tls:
    {{- range .Values.webapp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.webapp.ingress.hosts }}
    {{- range .Values.webapp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "s3www.fullname" $ }}-webapp
                port:
                  number: {{ $.Values.webapp.service.port }}
          {{- end }}
    {{- end }}
  {{- else if .Values.webapp.ingress.host }}
    - host: {{ .Values.webapp.ingress.host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "s3www.fullname" . }}-webapp
              port:
                number: {{ .Values.webapp.service.port }}
  {{- end }}
{{- end }}
