{{- if .Values.mcClientJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mc-client
  {{- if .Values.minio.namespace }}
  namespace: {{ .Values.minio.namespace }}
  {{- end }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
    app.kubernetes.io/component: mc-client
spec:
  ttlSecondsAfterFinished: {{ .Values.mcClientJob.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
      - name: minio-client
        image: "{{ .Values.mcClientJob.image.repository }}:{{ .Values.mcClientJob.image.tag }}"
        imagePullPolicy: {{ .Values.mcClientJob.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Wait for MinIO to be ready
            until mc config host add myminio http://minio-service:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --insecure; do
              echo "Waiting for MinIO to be ready..."
              sleep 5
            done
            
            # Create bucket if it doesn't exist
            mc mb myminio/{{ .Values.webapp.bucket }} --ignore-existing --insecure
            
            # Upload the HTML file from mounted ConfigMap
            mc cp /html-content/index.html myminio/{{ .Values.webapp.bucket }}/ --insecure

            # Verify upload
            mc ls myminio/{{ .Values.webapp.bucket }}/index.html --insecure

            echo "File uploaded successfully to MinIO"
        resources:
          {{- toYaml .Values.mcClientJob.resources | nindent 10 }}
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secretkey
        volumeMounts:
        - name: html-content
          mountPath: /html-content
        - name: minio-data
          mountPath: /data
      volumes:
      - name: html-content
        configMap:
          name: webapp-html-content
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
      restartPolicy: Never
{{- end }}
