apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3www.fullname" . }}-webapp
  {{- if .Values.webapp.namespace }}
  namespace: {{ .Values.webapp.namespace }}
  {{- end }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "s3www.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
